name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format:check
      - name: Run linter
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run tests with coverage
        run: npm test
      - name: Install coverage tools
        run: npm install -g codecov
      - name: Upload coverage
        run: codecov
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: psai
          environment-file: environment.yml
          auto-activate-base: false
      - name: Check imports
        run: conda run --no-capture-output isort --check src test
      - name: Check formatting
        run: conda run --no-capture-output black --check src test
      - name: Run linter
        run: conda run --no-capture-output pylint src test
      - name: Run type checker
        run: conda run --no-capture-output mypy src test
      - name: Run tests
        run: conda run --no-capture-output python -m test.unit
